version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.0
    steps:
      - run:
          name: "Setup Snyk"
          command: |
            sudo npm install -g snyk
      - run:
          name: "Checkout"
          command: |
            git clone https://github.com/aarlaud-snyk/github-stats
      - run:
          name: "Build"
          command: |
            cd github-stats
            npm install
      - run:
          name: "Test"
          command: |
            cd github-stats
            npm test
      - run:
          name: "Monitor"
          command: |
            cd github-stats
            snyk monitor --org=aarlaud-snyk
