version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.8.0
    steps:
      - run:
          name: "Setup Snyk"
          command: |
            sudo npm install -g snyk
      - checkout
      - run:
          name: "Install deps"
          command: |
            cd github-stats
            npm install
      - run:
          name: "Run Tests"
          command: |
            cd github-stats
            npm test
      - run:
          name: "Snyk Test"
          command: |
            cd github-stats
            snyk test --org=aarlaud-snyk
      - run:
          name: "Monitor"
          command: |
            cd github-stats
            snyk monitor --org=aarlaud-snyk
